import Head from "next/head";
import Navbar from "@/components/Navbar";
import Section from "@/components/Section";
import Intro from "@/components/Intro";

export default function Home() {
  return (
    <>
      <Head>
        <title>Datome</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar></Navbar>
        <Section style={{ backgroundColor: "#000" }}>
          <Intro padded></Intro>
        </Section>
      </main>
    </>
  );
}
